Greenshot/Languages/language-sk-SK.xml

make Slovak language Slovak, correct grammar and syntax

correct mistakes in language-sk-SK.xml

---

Greenshot/Languages/language-cs-CZ.xml

An update of CZ language file.

Several corrections and update for version 1.2.

---

Greenshot/Forms/MainForm.cs
Greenshot/Greenshot.csproj
Greenshot/Helpers/ResourceMutex.cs

Replaced Mutex code with a class from Dapplo.Addons which was written for Greenshot 1.3 "ResourceMutex", this should fix a few start-up issues.

Partial fix for BUG-1876 "already running"

---

Greenshot/releases/additional_files/license.txt

Text comes from here: https://www.gnu.org/licenses/gpl-3.0.txt

Change the GPL text to GPLv3

---

Greenshot/releases/innosetup/setup.iss.template

A change to the Registry permissions, this should solve a security vulnerability. Used the time to fix the file-type registration too.

BUG-1933 bad Registry permissions

---

GreenshotPlugin/Core/ClipboardHelper.cs

The maximum waiting time should now be 3 seconds.

BUG-1935: Increased the retry delay a bit more [skip ci]

---

GreenshotPlugin/Core/CoreConfiguration.cs
GreenshotPlugin/Core/ImageHelper.cs
GreenshotPlugin/Core/ImageOutput.cs

when writing, this will currently only write 256x256 .ico files!!!
These files are not supported by Windows XP and older!

FEATURE-916: Added support for .ico files

---

GreenshotJiraPlugin/AsyncMemoryCache.cs
GreenshotJiraPlugin/Forms/JiraForm.cs
GreenshotJiraPlugin/GreenshotJiraPlugin.csproj
GreenshotJiraPlugin/IssueTypeBitmapCache.cs
GreenshotJiraPlugin/JiraConnector.cs
GreenshotJiraPlugin/JiraDestination.cs
GreenshotJiraPlugin/packages.config
GreenshotPlugin/Core/NetworkHelper.cs

BUG-1811: Added icons for the issue type in the jira destination

---

GreenshotJiraPlugin/Forms/JiraForm.cs
GreenshotJiraPlugin/GreenshotJiraPlugin.csproj
GreenshotJiraPlugin/IssueTypeBitmapCache.cs
GreenshotJiraPlugin/JiraConnector.cs
GreenshotJiraPlugin/JiraPlugin.cs
GreenshotJiraPlugin/JiraUtils.cs
GreenshotJiraPlugin/LanguageKeys.cs
GreenshotJiraPlugin/SvgBitmapHttpContentConverter.cs
GreenshotJiraPlugin/packages.config
GreenshotPlugin/Core/Language.cs

need to decide if it's worth the extra KB's...

BUG-2016: Added SVG support for the jira plugin

---

Greenshot.Addon.Box/Languages/language_boxplugin-kab-DZ.xml

kab localization

---

Greenshot.Addon.Dropbox/Languages/language_dropboxplugin-kab-DZ.xml

Kab locale

---

Greenshot.Addon.Picasa/Languages/language_picasaplugin-kab-DZ.xml

Translation for Kabyle

---

Greenshot/Languages/language-cs-CZ.xml

This update was once lost and was not part of 1.2.8.14 release.

Czech language update

---

pages/impressum.markdown

Updated for impressum page

---

Greenshot.Addon.Imgur/Languages/language_imgurplugin-de-DE.xml

Corrected some german translations for the imgur plugin.

Corrections of german translation for imgur plugin

---

Greenshot/Languages/language-en-US.xml

Device Independend Bitmap -> Device Independent Bitmap

Typo fix in language-en-US.xml

---

src/Greenshot/Languages/language-cs-CZ.xml
src/Greenshot/Languages/language-en-US.xml
src/Greenshot/Languages/language-fr-QC.xml
src/Greenshot/Languages/language-id-ID.xml
src/Greenshot/Languages/language-it-IT.xml
src/Greenshot/Languages/language-lv-LV.xml
src/Greenshot/Languages/language-pt-PT.xml
src/Greenshot/Languages/language-ru-RU.xml
src/Greenshot/Languages/language-sk-SK.xml
src/Greenshot/Languages/language-sv-SE.xml
src/Greenshot/Languages/language-zh-TW.xml

Correct "Device Independend Bitmap" to "Device Independent Bitmap"

Fix typo for DIB in language files

---

src/Greenshot.Addon.OneDrive/Languages/language_onedriveplugin-kab-DZ.xml

Create  	language_onedriveplugin-kab-DZ.xml

---

src/Greenshot.Addon.Office/OfficeAddonModule.cs

I spotted a couple of typos that [hopefully] I've corrected.
Thank you for allowing me to make my first GitHub changes!  :-)
Lee

BUG-2440 Corrected typos

---

src/Greenshot.Addons/Components/ExportNotification.cs

Small correction.
Argument with index 1 does not exists in argument list.

Fix msg for FormatException

---

src/Greenshot/Languages/Help/help-pt-BR.html
src/Greenshot/Languages/Installer/language-installer-pt-BR.xml
src/Greenshot/Languages/Website/language-website-pt-BR.xml
src/Greenshot/Languages/language-pt-BR.xml

Updated and added Brazilian Portuguese language to help, installer and wabsite.

Update Brazilian Portuguese and translate help files

---

src/Greenshot.Addon.LegacyEditor/Drawing/FreehandContainer.cs
src/Greenshot.Gfx/Legacy/ScaleHelper.cs

Fixed Freehand, Rectangle and Ellipse tools in the Image editor.

Fix image editor tools.

---

README.md

Fix .NET Version in readme

---

src/Greenshot/Languages/language-it-IT.xml

Keep Italian language aligned as number/order of strings with English
Translated new strings
Revised some existing translations
@Lakritzator 
Please merge.

Update Italian language

---

Greenshot/Drawing/Fields/Binding/DecimalFloatConverter.cs
Greenshot/Drawing/Fields/Binding/DecimalIntConverter.cs

Converters fix for release 1.3

---

Greenshot/Languages/language-it-IT.xml
Greenshot/Languages/website/language-website-it-IT.xml
Greenshot/releases/innosetup/scripts/lang/italian.iss
GreenshotBoxPlugin/Languages/language_boxplugin-it-IT.xml
GreenshotConfluencePlugin/Languages/language_confluenceplugin-it-IT.xml
GreenshotDropboxPlugin/Languages/language_dropboxplugin-it-IT.xml
GreenshotExternalCommandPlugin/Languages/language_externalcommandplugin-it-IT.xml
GreenshotFlickrPlugin/Languages/language_flickrplugin-it-IT.xml
GreenshotImgurPlugin/Languages/language_imgurplugin-it-IT.xml
GreenshotJiraPlugin/Languages/language_jiraplugin-it-IT.xml
GreenshotOCRPlugin/Languages/language_ocrplugin-it-IT.xml
GreenshotPhotobucketPlugin/Languages/language_photobucketplugin-it-IT.xml
GreenshotPicasaPlugin/Languages/language_picasaplugin-it-IT.xml

@Lakritzator 
I made a single PR with all language files update regarding
installer
GUI
website
plugins
Please merge. Thanks.

italian language files update

---

src/Greenshot/Languages/language-it-IT.xml

Reverts greenshot/greenshot#235

Revert "Update Italian language"

---

Greenshot/Languages/language-it-IT.xml

@Lakritzator 
Align strings numbers (Add a new string)
Add refence about translation date
Please merge.

Italian language update

---

Greenshot/Languages/language-it-IT.xml

@Lakritzator 
Update Italian language (removed double string)
Please merge,. Thanks.

Update Italian language (removed double string)

---

Greenshot/releases/innosetup/setup.iss

@Lakritzator 
Add changes to have icon description for Readme/License multi-language
Add Italian translation for the icon descriptions.
Please merge, Thanks.

Update installer script

---

src/Greenshot.Addon.ExternalCommand/ExternalCommandDestination.cs
src/Greenshot.Addon.ExternalCommand/Greenshot.Addon.ExternalCommand.csproj

Updated CliWrap to latest version and simplified its usage with `ConfigureAwait()`

Simplify CliWrap usage

---

Greenshot/Languages/language-en-US.xml

@Lakritzator 
Add strings for "about_translation" (useful for translator).
This string available in other languages.
Please merge.

Update English language

---

Directory.Build.props
Greenshot/Greenshot.csproj
GreenshotJiraPlugin/GreenshotJiraPlugin.csproj
GreenshotJiraPlugin/JiraConnector.cs
GreenshotPlugin/Core/ImageHelper.cs
GreenshotPlugin/GreenshotPlugin.csproj

Fix an issue when running Greenshot via Wine

---

Directory.Build.props
Greenshot/Greenshot.csproj
Greenshot/Helpers/MailHelper.cs
GreenshotJiraPlugin/GreenshotJiraPlugin.csproj
GreenshotPlugin/Core/EmailConfigHelper.cs
GreenshotPlugin/Core/RegistryHelper.cs
GreenshotPlugin/Core/RegistryKeyExtensions.cs
GreenshotPlugin/GreenshotPlugin.csproj

This should fix an issue where Greenshot doesn't detect a MAPI client, we weren't looking at the 32 bit location.

BUG-2693: Fix for MAPI detection

---

Greenshot/Languages/help-it-IT.html

@Lakritzator 
Please check and merge. Thanks.

Update Help (IT)

---

installer/innosetup/setup.iss

Changed from Ceština into Čeština.

Corrected czech translation

---

src/Greenshot/Languages/language-cs-CZ.xml

I just reviewed that language file and updated with latest strings from en_us file, also corrected and reviewed used terminology in application.

Update of Czech language file

---

pages/help.markdown

tag was missing nesting was off

Fix missing paragraph tag

---

_faqs/2017-01-29-excluding-plugin-destination.markdown

This is the user documentation for #644

Follow-up docu for #644
