greenshot/greenshot

Greenshot/Forms/ImageEditorForm.Designer.cs, Greenshot/Forms/ImageEditorForm.cs, Greenshot/releases/additional_files/readme.txt.template
Add right click on drop-shadow or torn-edge brings up the settings, left-click or the hotkey (Ctrl + Q for Dropshadow, Ctrl + T for Torn-Edge) will apply directly with the previous/default settings.
=> BUG-1762, FEATURE-964, FEATURE-860 - Skip settings torn-edge & drop shadow

_includes/head.html
Head now includes link rel="canonical" element, so that public forks of the repo (duplicating our content) don't hurt our search engine ranking.
=> Added canonical link to getgreenshot.org

README.md
The current hyperlink in the README links to http://getgreenshot.org/support-greenshot/ (which 404s) while the actual support link is http://getgreenshot.org/support/. This pull request simply updates that link in the README file.
=> Fixing the hyperlink in the README to correctly link to support page

src/Greenshot.Addon.OneDrive/Entities/OneDriveGetLinkRequest.cs, src/Greenshot.Addon.OneDrive/Entities/OneDriveGetLinkResponse.cs, src/Greenshot.Addon.OneDrive/Greenshot.Addon.OneDrive.csproj, src/Greenshot.Addon.OneDrive/IOneDriveConfiguration.cs, src/Greenshot.Addon.OneDrive/IOneDriveLanguage.cs, src/Greenshot.Addon.OneDrive/Languages/language_onedriveplugin-en-US.xml, src/Greenshot.Addon.OneDrive/OneDriveDestination.cs, src/Greenshot.Addon.OneDrive/ViewModels/OneDriveConfigViewModel.cs, src/Greenshot.Addon.OneDrive/Views/OneDriveConfigView.xaml
OneDrive improvements:
UI:
* Removed unused language properties (maybe they are needed but I just didn't know?)
* Added OneDriveLinkType selection
* Added reset credentials button
Destination:
* Support public and organization links - additional call was needed to retrieve them
=> Onedrive addon improvements - UI, public&organization link type

src/Greenshot/Languages/language-zh-TW.xml
The previous translation translates "hosted by" wrong, this patch fixes it.
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
=> Fix Traditional Chinese(Taiwan) translation

src/Greenshot.Tests/CaptureTests.cs
Removed capture test being dependent on some Notepad window. Test was only successfull if this window existed (had to open it manually).
Code from [your dapplo repo](https://github.com/dapplo/Dapplo.Windows/blob/450fae4b4a139b2bf6063bbbc6c40772355d4c0d/src/Dapplo.Windows.Tests/WindowsEnumeratorTests.cs#L85)
PS: Great seeing you working on Greenshot 2.0. Keep up the good work. Thanks to your recent changes, I was finally able to finish a build. With this small change all tests are successfull now.
=> Removed external test dependency

src/Greenshot.Addon.LegacyEditor/Drawing/TextContainer.cs
Fixing issue in textbox when typing ALTGR+A (polish letter ą) raised in threads BUG-2288, BUG-2474.
=> Fixing textbox issue with polish letter ą

src/Greenshot.Addons/Views/FileConfigPartView.xaml
Notes from accessibility testing:
Defect: Information is conveyed solely via a sensory characteristic.
Description: Please see example below for details.
Expected result: Information is expected to not rely solely on sensory characteristics such as size, shape, sound, or visual orientation. In this instance, additional information such as text or labeling is expected to be provided for the three dot button.
Reference: Section 508, 1.3.3 – Sensory Characteristics.    
For more information, visit: http://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-understanding.html
Steps to reproduce:
1.       Open Greenshot v1.2.10.6
2.       Select “Preferences…” link.
3.       Navigate to the “Output” tab.
Notice that no additional information such as text or labeling is provided for …
=> Add a tooltip for file output path selection

src/Greenshot.Addon.LegacyEditor/Drawing/Fields/Binding/DecimalFloatConverter.cs, src/Greenshot.Addon.LegacyEditor/Drawing/Fields/Binding/DecimalIntConverter.cs, src/Greenshot.Addon.LegacyEditor/Drawing/Fields/FieldTypes.cs
This looks like a copy-paste error. Font size is supposed to be a float, judging from the rest of the code. Wrong type here causes exceptions.
Side note: both DecimalIntConverter and DecimalFloatConverter also look like someone wasn't paying attention. `Decimal --> (explicit) Int16 --> (implicit) Float` conversion causes no issues only due to the fact all numbers effectively are small integers.
=> Font size field type fix

src/Greenshot/Languages/language-en-US.xml
Fixes a minor typo on the term 'Windows 7' in the English language files.
=> Fixes a minor typo in the English language files

Greenshot/Languages/language-en-US.xml, GreenshotPlugin/Core/FilenameHelper.cs
This pull request resolves [FEATURE-762](https://greenshot.atlassian.net/browse/FEATURE-762) by adding the `${RR...}` filename placeholder.
The en-US language file for pattern help is updated, but I'm not sure how to request translations for the others. Improvements to the wording are welcome.
=> Add placeholder for random alphanumerics in filename

Greenshot/Drawing/TextContainer.cs
In #283 it was reported that Greenshot doesn't draw unicode icons correctly. this should solve it.
=> Fix Unicode text drawing

Greenshot/Drawing/TextContainer.cs
When moving from graphics.DrawString to TextRenderer.DrawText, to fix #283, the line wrapping was broken. This should fix it.
=> Fix text rendering inside text / speech bubble containers

src/Greenshot.Editor/Drawing/EllipseContainer.cs, src/Greenshot.Editor/Drawing/HighlightContainer.cs
Fixes #322.
Ellipse only created default adorners in constructor, never after deserialization. Having zero adorners triggered a Linq exception down the code path. Fixed by duplicating the deserialization logic from RectangleContainer.
Highlight also failed to create its default adorners. Fixed by just adding a correct call to CreateDefaultAdorners in the existing Init method.
=> Fix Ellipse and Highlight duplication bug (#322).

src/Greenshot.Base/Interfaces/Drawing/IDrawableContainer.cs, src/Greenshot.Editor/Drawing/CropContainer.cs, src/Greenshot.Editor/Drawing/DrawableContainer.cs, src/Greenshot.Editor/Drawing/Surface.cs
Property IsConfirmable added for IDrawableContainer to indicate whether confirm/cancel is available.
To avoid System.NotImplementedException when pressing esc/enter on a container that does not support it.
Solve #397
=> IsConfirmable for IDrawableContainer

src/Greenshot.Editor/Drawing/CropContainer.cs
Bugfix crop selection scaling #404
Disable scaling for horizontal and vertical crop modes, as it makes no sense in these cases.
Btw, but I think this is known as I read the last commit. The centered scaling does nothing. It inflates the rectangle all times by 0.
=> Fix initial crop selection

src/Greenshot.Base/Core/PluginUtils.cs, src/Greenshot.Plugin.Office/Destinations/ExcelDestination.cs, src/Greenshot.Plugin.Office/Destinations/OneNoteDestination.cs, src/Greenshot.Plugin.Office/Destinations/OutlookDestination.cs, src/Greenshot.Plugin.Office/Destinations/PowerpointDestination.cs, src/Greenshot.Plugin.Office/Destinations/WordDestination.cs
Changes to FIX BUG2951. Some newer Office installations use a different registry keys and some corporate GPOs block Office installation to write onto the Apps registry key. Changed the code so that the program looks in both the Apps path and the more standard OfficeInstall registry keys. This version was tested in Windows 8.1, Windows 10 and Windows 11 with no issues.
=> Fix of BUG2951

installer/innosetup/setup.iss
Hi there, inspired from #482 and with the help of ChatGPT I hacked out the installer to disable the PrtScr default tool on Windows 11 installations. It is shown as an extra option if you're on Win11 >= Build 22000. This can be refined further if required. Built and tested on wdk2023, arm64 - the PR is platform independent, though.
=> add install option to disable the default win11 prtscr tool

src/Greenshot.Base/Interfaces/Plugin/AssemblyPluginIdentifierAttribute.cs, src/Greenshot.Plugin.Confluence/Properties/AssemblyInfo.cs, src/Greenshot.Plugin.Dropbox/Properties/AssemblyInfo.cs, src/Greenshot.Plugin.ExternalCommand/Properties/AssemblyInfo.cs, src/Greenshot.Plugin.Flickr/Properties/AssemblyInfo.cs, src/Greenshot.Plugin.GooglePhotos/Properties/AssemblyInfo.cs, src/Greenshot.Plugin.Imgur/Properties/AssemblyInfo.cs, src/Greenshot.Plugin.Jira/Properties/AssemblyInfo.cs, src/Greenshot.Plugin.Office/Properties/AssemblyInfo.cs, src/Greenshot.Plugin.Photobucket/Properties/AssemblyInfo.cs, src/Greenshot.Plugin.Win10/Properties/AssemblyInfo.cs, src/Greenshot/Helpers/PluginHelper.cs
This fixes #642.
The list of plugin names, as described in the [FAQ](https://getgreenshot.org/faq/how-remove-plugins-or-destinations-from-greenshot/), is no longer available.
I have defined a new way that extracts the name from the plugin's sub-namespace.
This is the new current list:
```
"Box"
"Confluence"
"Dropbox"
"ExternalCommand"
"Flickr"
"GooglePhotos"
"Imgur"
"Jira"
"Office"
"Photobucket"
"Win10"
```
I intentionally omitted the suffix `“ Plugin”` as it was previously included.
=> Fix: Define plugin name for exclusion in INI

src/Greenshot/Helpers/CopyData.cs
Added all missing types to `SafeSerializationBinder` that are allowed to be sent with WM_COPYDATA.
This fixes #685
=> [Fix] Missing types in SafeSerializationBinder 
